# http://module-build.sourceforge.net/META-spec.html
name:         MojoX-AIO
version:      0.05
version_from: lib/MojoX/AIO.pm
installdirs:  site
requires:
    Carp:
    IO::AIO: 2
    Mojolicious: 1.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
