# http://module-build.sourceforge.net/META-spec.html
name:         MojoX-AIO
version:      0.01
version_from: lib/MojoX/AIO.pm
installdirs:  site
requires:
    Carp:
    IO::AIO:
    Mojolicious:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
